[package]
name = "dyn-comp-dtif"
version = "0.0.1"
description = ""
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = "Commercial License"
authors = { workspace = true }

[features]
default = []
tracing = []

[dependencies]
dyn-comp-bundles = { path = "../comp_bundles", features = ["serde_support"] }
dyn-utils = { path = "../utils", features = ["serde_support"] }
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_hierarchy = { workspace = true }
bevy_transform = { workspace = true }
tiny-skia-path = { workspace = true }
glam = { workspace = true }
piccolo = { git = "https://github.com/kyren/piccolo", rev = "df3e53e" }
gc-arena = { version = "0.5.3", features = ["allocator-api2", "hashbrown"] }

# Bindgen
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, features = ["serde", "glam"] }

# Logging
log = { workspace = true }

[dev-dependencies]
env_logger = "0.11.3"
