[package]
name = "dyn_svg_composition_api"
version = "0.0.1"
edition = "2021"
description = "SVG Composition"
homepage = "https://s.dyn.art/github"
repository = "https://github.com/dyndotart/monorepo"
license = "AGPL-3.0-or-later"
authors = ["@bennoinbeta"]

[lib]
name = "dyn_svg_composition_api"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[features]
default = []
console_log = ["dep:console_error_panic_hook", "dep:once_cell"]
tracing = ["console_log", "dyn_composition/tracing", "dyn_svg_render/tracing"]
cli = ["dep:clap", "specta/export"]

[dependencies]

# Core dependencies
dyn_composition = { path = "../../../crates/composition", features = [
    "interactive",
] }
dyn_svg_render = { path = "../../../crates/svg_render" }
dyn_bevy_render_skeleton = { path = "../../../crates/bevy_render_skeleton" }
bevy_ecs = "0.12.1"
bevy_app = "0.12.1"
serde = { version = "1.0.195", features = ["derive"] }

# Logging
log = "0.4.20"
once_cell = { version = "1.19.0", optional = true }

# Bindgen dependencies
wasm-bindgen = "0.2.89"
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3.66"
serde_json = "1.0.111"
serde-wasm-bindgen = "0.6.3"

# CLI dependencies
clap = { version = "4.4.16", features = ["derive"], optional = true }
specta = { version = "2.0.0-rc.7", features = [
    "typescript",
    "serde",
    "glam",
    "bevy_ecs",
    "functions",
] }

[dev-dependencies]
wasm-bindgen-test = "0.3.39"

[profile.release]
opt-level = "s"
lto = true

[profile.dev.package."*"]
opt-level = 3
