[package]
name = "dyn-web-api"
version = "0.0.1"
description = ""
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[lib]
path = "rust/lib.rs"

[[bin]]
name = "crab"
path = "api/crab.rs"

[features]
default = []
tracing = [
    "dyn-comp-core/tracing",
    "dyn-comp-svg-builder/tracing",
    "dyn-comp-dtif/tracing",
]

[dependencies]
dyn-comp-asset = { path = "../../crates/comp_asset" }
dyn-comp-core = { path = "../../crates/comp_core", features = ["dtif"] }
dyn-comp-dtif = { path = "../../crates/comp_dtif" }
dyn-comp-bundles = { path = "../../crates/comp_bundles", features = [
    "serde_support",
] }
dyn-comp-svg-builder = { path = "../../crates/comp_svg_builder", features = [
    "serde_support",
] }
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_transform = { workspace = true }
tokio = { version = "1.36.0", features = ["macros"] }
serde_json = { version = "1.0.115", features = ["raw_value"] }
vercel_runtime = { version = "1.1.1" }

# Logging
log = { workspace = true }
