[package]
name = "specta-test"
version = "0.0.1"
description = ""
edition = "2021"

[lib]
name = "specta_test"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[features]
default = []

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
specta = { version = "2.0.0-rc.7", features = [
    "typescript",
    "serde",
    "export",
] }

[profile.release]
opt-level = "s"
lto = true

[profile.dev.package."*"]
opt-level = 3
