import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo'
};

const RootLayout: React.FC<TProps> = (props) => {
	const { children } = props;
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
};

export default RootLayout;

interface TProps {
	children: React.ReactNode;
}
