[package]
name = "dyn-dtif"
version = "0.0.1"
description = ""
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[features]
default = []
tracing = []

[dependencies]
dyn-comp-types = { path = "../comp_types", features = ["serde_support"] }
glam = "0.25.0"
smallvec = "1.13.1"
serde = { version = "1.0.195", features = ["derive"] }
specta = { git = "https://github.com/oscartbeaumont/specta.git", rev = "5da3e56e82addf972766a7be8af720a2f5d2ca17", features = [
    "serde",
    "glam",
], optional = true }
