[package]
name = "dyn_composition"
version = "0.0.1"
edition = "2021"
description = "Description of the package"
homepage = "https://dyn.art/github"
repository = "https://github.com/dyndotart/monorepo"
license = "AGPL-3.0-or-later"
authors = ["@bennoinbeta"]

[features]
default = []
trace = []

[dependencies]
bevy_ecs = "0.12"
bevy_app = "0.12"
bevy_utils = "0.12"
bevy_hierarchy = "0.12"
serde = { version = "1.0.189", features = ["derive"] }
glam = { version = "0.24.2", features = ["serde"] }
log = "0.4.20"
dyn_bevy_render_skeleton = { path = "../bevy_render_skeleton" }
specta = { path = "/Users/benno/Desktop/workspace/contribution/code/specta", features = [
    "typescript",
    "serde",
    "glam",
    "bevy_ecs",
] }
