[package]
name = "dyn-dtom"
version = "0.0.1"
authors = ["BennoDev <57860196+bennoinbeta@users.noreply.github.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.87"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
bevy_ecs = "0.11.3"
bevy_app = "0.11.3"
bevy_utils = "0.11.3"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
js-sys = "0.3.64"
serde-wasm-bindgen = "0.6.0"
glam = { version = "0.24.2", features = ["serde"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
