[package]
name = "dyn_dtom"
version = "0.0.1"
edition = "2021"
description = "Description of the package"
homepage = "https://dyn.art/github"
repository = "https://github.com/dyndotart/monorepo"
license = "AGPL-3.0-or-later"
authors = ["@bennoinbeta"]

[lib]
name = "dyn_dtom"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"
path = "src/bin.rs"

[features]
default = []
console_log = ["console_error_panic_hook", "js-sys"]
trace = ["console_log"]
cli = ["clap", "specta/export"]

[dependencies]
wasm-bindgen = "0.2.87"
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

# App dependencies
bevy_ecs = "0.12"
bevy_app = "0.12"
bevy_utils = "0.12"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
js-sys = { version = "0.3.64", optional = true }
serde-wasm-bindgen = "0.6.0"
glam = { version = "0.24.2", features = ["serde"] }
once_cell = "1.18.0"
log = "0.4.20"
dyn_bevy_render_skeleton = { path = "../../../crates/bevy_render_skeleton" }

specta = { path = "/Users/benno/Desktop/workspace/contribution/code/specta", features = [
    "typescript",
    "serde",
    "glam",
    "bevy_ecs",
] }
# CLI dependencies
clap = { version = "4.4.6", features = ["derive"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[profile.release]
opt-level = "s"
lto = true

[profile.dev.package."*"]
opt-level = 3
