[package]
name = "dyn_comprender"
version = "0.0.1"
description = "Composition Render API"
edition = "2021"
homepage = "https://s.dyn.art/github"
repository = "https://github.com/dyndotart/monorepo"
license = "AGPL-3.0-or-later"

[features]
default = []
tracing = ["dyn_composition/tracing", "dyn_svg_render/tracing"]
cli = ["dep:clap"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "dyn_comprender"    # Needs to be called like the package so that the Dockerfile can work with `dyn_[name]` pattern
path = "src/bin/server.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[dependencies]

# Core dependencies
dyn_composition = { path = "../../crates/composition", features = [
    'resolve-url',
] }
dyn_svg_render = { path = "../../crates/svg_render" }
dyn_bevy_render_skeleton = { path = "../../crates/bevy_render_skeleton" }
axum = "0.7.3"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }
specta = "2.0.0-rc.7"
dotenv_config = "0.1.8"
dotenvy = "0.15.7"
resvg = "0.37.0"
usvg = "0.37.0"
tiny-skia = "0.11.3"
reqwest = "0.11.23"
svg2pdf = "0.9.1"

# CLI dependencies
clap = { version = "4.4.16", features = ["derive"], optional = true }
utoipa = { version = "4.2.0", features = ["axum_extras"] }

[profile.release]
opt-level = "s"
lto = true

[profile.dev.package."*"]
opt-level = 3
