[package]
name = "dyn_comprender"
version = "0.0.1"
edition = "2021"
description = "Composition Render API"
homepage = "https://s.dyn.art/github"
repository = "https://github.com/dyndotart/monorepo"
license = "AGPL-3.0-or-later"

[dependencies]
dyn_composition = { path = "../../crates/composition", features = [
    'resolve-url',
] }
dyn_svg_render = { path = "../../crates/svg_render" }
dyn_bevy_render_skeleton = { path = "../../crates/bevy_render_skeleton" }
axum = "0.7.3"
# bevy_ecs = "0.12"
# bevy_app = "0.12"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }
specta = "2.0.0-rc.7"
dotenv_config = "0.1.8"
dotenvy = "0.15.7"
resvg = "0.37.0"
usvg = "0.37.0"
tiny-skia = "0.11.3"
reqwest = "0.11.23"
