[package]
name = "dyn-svg-comp-api"
version = "0.0.1"
description = ""
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[lib]
name = "dyn_svg_comp_api"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"
path = "src/bin/cli.rs"
required-features = ["cli"]

[features]
default = []
console_log = ["dep:console_error_panic_hook", "dep:once_cell"]
cli = ["dep:clap", "specta/export"]
tracing = [
    "console_log",
    "dyn-comp-core/tracing",
    "dyn-comp-interaction/tracing",
    "dyn-comp-svg-builder/tracing",
    "dyn-comp-dtif/tracing",
]

[dependencies]
dyn-comp-core = { path = "../../../v2/comp_core", features = ["dtif"] }
dyn-comp-dtif = { path = "../../../v2/comp_dtif" }
dyn-comp-types = { path = "../../../v2/comp_types", features = [
    "serde_support",
] }
dyn-comp-interaction = { path = "../../../v2/comp_interaction", features = [
    "serde_support",
] }
dyn-comp-svg-builder = { path = "../../../v2/comp_svg_builder", features = [
    "serde_support",
    "output_svg_element_changes",
] }
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
log = { workspace = true }
wasm-bindgen = "0.2.91"
js-sys = "0.3.68"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.114"
serde-wasm-bindgen = "0.6.4"

# console_log
console_error_panic_hook = { version = "0.1.7", optional = true }
once_cell = { version = "1.19.0", optional = true }

# cli
clap = { version = "4.5.1", features = ["derive"], optional = true }
specta = { workspace = true, features = [
    "typescript",
    "serde",
    "glam",
    "bevy_ecs",
    "functions",
] }

[dev-dependencies]
wasm-bindgen-test = "0.3.41"

[profile.release]
opt-level = "s"
lto = true

[profile.dev.package."*"]
opt-level = 3
