[package]
name = "dyn-comp-dtif"
version = "0.0.1"
description = ""
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[features]
default = []
tracing = []

[dependencies]
dyn-comp-types = { path = "../comp_types", features = ["serde_support"] }
bevy_ecs = { workspace = true }
bevy_hierarchy = { workspace = true }
bevy_transform = { workspace = true }
glam = { workspace = true }
smallvec = { workspace = true }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["serde", "glam"] }
